### PR TITLE
feat: support .each suite execution by regex

### PR DESCRIPTION
**Pull request by keroxp**
Support an execution of `.each` describe/test suite that includes `%` placeholders. vitest `--testNamePattern` opts doesn't recognize pattern with`%` placeholders. So we need to transform the given suite name by replacing `%` to `.+` regexp.

The base branch of this PR is #213.

### CODE REVIEW

**Comment by MilanKovacic** [comment]
Fixes https://github.com/vitest-dev/vscode/issues/7.

**Comment by keroxp** [comment]
Additionally, Incomplete edge cases still remain. Similar describe/test cases will be matched by the same transformed regular expression. Like:

```
(1) test.each([...])("my test %s)(() => {})
(2) test.each([...])("my test will be %s")(()=>{})
```

(2) is also executed by executing (1) and got no result, showing error, because (1) goes to `my test .+?`.

**Comment by sheremet-va** [comment]
Thank you for your contribution! Can you resolve conflicts, when you have the time, please? 🙏🏻

**Comment by keroxp** [comment]
Backed to WIP, still refactoring.

**Review by ffMathy — APPROVED** [review]
LGTM! I love this. Initially I was skeptical of the use of regex, but after seeing the implementation, it should be stable.

**Comment by ffMathy** [comment]
@keroxp, @sheremet-va wants to know if we can merge this?

**Review by sheremet-va — APPROVED** [review]

**Comment by ffMathy** [comment]
This introduces a bug. When there are more describes with the same name, you can't run the tests in the last describe.

Example repro:

```typescript
import { describe, expect, it } from 'vitest'
import { add } from '../src/add'

describe('duplicate describe', () => {
  it('test 1', () => {
    expect(add(1, 1)).toBe(2)
  })
})

describe('duplicate describe', () => {
  it('test 2', () => {
    expect(add(1, 1)).toBe(2)
  })
})
```

With the above, "test 2" can't be run and will give an error. This worked before.

**Comment by ffMathy** [comment]
cc @keroxp. Got an idea for a fix? I tried, but can't understand the code.

**Pull request merged**
