### PR TITLE
Enhance issue reporting template with version validation

### PR DESCRIPTION
**Pull request by MilanKovacic**
This PR introduces a validation step in the issue reporting template to ensure that issues are reported against the latest version of the extension. The rationale behind this change is to streamline the issue resolution process by focusing efforts on current problems, reducing the time spent on issues already addressed in recent updates, and encouraging users to keep their installations updated.

### CODE REVIEW

**Comment by sheremet-va** [comment]
Do we need the version input now?

**Comment by ffMathy** [comment]
The version output, doesn't that only include the Vitest packages? This would be for the version of the extension itself.

**Comment by ffMathy** [comment]
The version output, doesn't that only include the Vitest packages? This would be for the version of the extension itself.

**Comment by sheremet-va** [comment]
> The version output, doesn't that only include the Vitest packages? This would be for the version of the extension itself.

Please, look at the current issue template. It has "Output" (logs from the "Output" window) and "Version" fields. If we include this check, then why do we need the "Version" field?

**Comment by MilanKovacic** [comment]
The primary reason for keeping the version field, even with the required version validation step, is to ensure we can easily see the specific extension version that the issue was reported against.

Over time, the "latest version" information from the validation step may become less meaningful. The version field provides a clear, accessible record of the exact version used when the issue was reported.

**Pull request merged**
