### PR TITLE
Create devcontainer.json

### PR DESCRIPTION
**Pull request by willj5t6969**

### CODE REVIEW

**Comment by sheremet-va** [comment]
What is that?

**Comment by ffMathy** [comment]
Honestly @sheremet-va a devcontainer wouldn't be a bad idea. They are amazing.

**Comment by sheremet-va** [comment]
> Honestly @sheremet-va a devcontainer wouldn't be a bad idea. They are amazing.

Let's stop assuming that we share the same knowledge of what dev containers are and how they are useful. The description of this PR is empty - no cons, not pros, no description of why it's being added, no guide on how to use it, not even what it is.

**Comment by ffMathy** [comment]
https://letmegooglethat.com/?q=devcontainer

**Comment by sheremet-va** [comment]
> [letmegooglethat.com?q=devcontainer](https://letmegooglethat.com/?q=devcontainer)

I'll just say that I find this behavior offensive. I am supporting several repositories with hundreds of issues. I do not have time to study some "amazing" ideas just because someone left a comment.

**Pull request closed without merging**
